/**
 * VYNTRA — SOS Decoder Module
 * Parses compact SOS payload generated by Part 1, validates format,
 * separates coordinates, and maps condition codes to priority triage tiers.
 */

import { decodeSOS, SOS_CONDITIONS } from '../../shared/constants/sos-codes';

export interface DecodedSOSTelemetry {
  rawCode: string;
  lat: number;
  lng: number;
  userId: string;
  timestamp: number;
  timestampDate: Date;
  elapsedTimeString: string;
  conditions: Array<{
    code: string;
    label: string;
    priorityTier: 'p1' | 'p2' | 'p3';
  }>;
  overallPriority: 'p1' | 'p2' | 'p3';
  priorityLabel: string;
}

/**
 * Maps condition codes to triage priority tiers.
 * P1 = Urgent/Immediate life safety (rose-coral)
 * P2 = High attention / Elderly / Child / Mobility (amber)
 * P3 = Standard care / Sanitation / Supplies (plum-lavender)
 */
export function getPriorityTier(code: string): 'p1' | 'p2' | 'p3' {
  switch (code) {
    case 'PG': // Pregnancy
    case 'AD': // Acute Distress
    case 'MD': // Medical Difficulty
      return 'p1';
    case 'WC': // Wheelchair Required
    case 'CC': // Child Care Required
    case 'EA': // Elderly Assistance
      return 'p2';
    case 'MN': // Menstruation
    case 'VM': // Vomiting
    case 'HC': // Healthcare Support Needed
    case 'SN': // Sanitation Required
    default:
      return 'p3';
  }
}

/**
 * Computes human-readable elapsed time string (e.g. '3 mins ago').
 */
function getElapsedString(timestampSeconds: number): string {
  const diffSeconds = Math.max(0, Math.floor(Date.now() / 1000 - timestampSeconds));
  if (diffSeconds < 60) return `${diffSeconds}s ago`;
  const diffMins = Math.floor(diffSeconds / 60);
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
}

/**
 * Decodes and validates a compact SOS code string.
 */
export function parseSOSMessage(code: string): DecodedSOSTelemetry | null {
  const trimmed = code.trim();
  const decoded = decodeSOS(trimmed);
  if (!decoded) return null;

  const conditionsWithTriage = decoded.conditions.map((c) => ({
    code: c.code,
    label: c.label || SOS_CONDITIONS[c.code] || 'Emergency Support Needed',
    priorityTier: getPriorityTier(c.code),
  }));

  // Determine overall triage priority (highest among conditions)
  let overallPriority: 'p1' | 'p2' | 'p3' = 'p3';
  if (conditionsWithTriage.some((c) => c.priorityTier === 'p1')) {
    overallPriority = 'p1';
  } else if (conditionsWithTriage.some((c) => c.priorityTier === 'p2')) {
    overallPriority = 'p2';
  }

  const priorityLabel =
    overallPriority === 'p1'
      ? 'P1 — Urgent Emergency Response'
      : overallPriority === 'p2'
      ? 'P2 — Priority Vulnerable Assistance'
      : 'P3 — General Emergency Relief';

  return {
    rawCode: trimmed,
    lat: decoded.lat,
    lng: decoded.lng,
    userId: decoded.userId,
    timestamp: decoded.timestamp,
    timestampDate: new Date(decoded.timestamp * 1000),
    elapsedTimeString: getElapsedString(decoded.timestamp),
    conditions: conditionsWithTriage,
    overallPriority,
    priorityLabel,
  };
}
